#!/bin/bash
set -e

# Microsoft repo (Debian/Ubuntu base)
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list

apt-get update
ACCEPT_EULA=Y apt-get install -y msodbcsql18

# opcional: ferramentas
# ACCEPT_EULA=Y apt-get install -y mssql-tools18